export default /*tw*/ {
  wrapper: {
    base: "relative bg-white rounded-lg",
    variants: {
      compact: {
        true: "group/table-compact",
      },
    },
  },
  headerCheckboxWrapper: "",
  header: "border-b border-gray-200",
  headerRow: "",
  headerCell: "p-4 text-sm font-normal text-gray-500 text-left",
  headerSelectAllCheckbox: "",
  stickyHeader: "flex items-center z-30 overflow-hidden rounded-t-lg border border-gray-200 border-b-0",
  stickyHeaderHidden: "relative -top-[3.75rem] collapse",
  stickyHeaderLoader: "absolute top-[3.75rem] group-[]/table-compact:!top-[3.25rem]",
  stickyHeaderActive: "fixed top-0 border  border-gray-200 bg-white rounded-none",
  stickyHeaderActions: "rounded-t-lg border border-blue-200 !bg-blue-50",
  stickyHeaderColumn: "flex-none text-sm font-normal text-gray-500 p-4 whitespace-nowrap",
  selectedRowsCount: "absolute left-11 pr-2 font-medium text-sm text-gray-900 bg-gradient-to-r from-white from-80%",
  selectAllCheckbox: "flex-none text-sm font-normal text-gray-500 pr-[1.125rem] pl-4 py-4 group-[]/table-compact:!px-4",
  innerWrapper: "!overflow-visible rounded-lg border border-gray-200",
  innerWrapperSelected: "!rounded-t-none border-t-0",
  table: "min-w-full border-none text-sm w-full",
  tableLoader: "absolute !top-auto",
  moreRow: "!px-0 !py-4 first:mx-auto",
  moreRowHidden: "!p-0",
  checkedRow: "transition duration-100 bg-gray-100",
  beforeFirstRow: "",
  beforeFirstRowCell: "py-1",
  afterLastRow: "",
  afterLastRowCell: "py-1",
  toggleButtonWrapper: "flex items-center",
  expandIcon: "mr-2 rounded-sm bg-gray-200",
  expandIconName: "add",
  collapseIcon: "mr-2 rounded-sm bg-gray-200",
  collapseIconName: "remove",
  body: "group/body divide-none",
  bodyRow: "hover:bg-gray-50",
  checkboxBodyWrapperCell: "py-3 px-4 align-top",
  bodyCell: "",
  tableCheckbox: "",
  dateSeparator: "",
  toggleItemButton: "flex relative -top-px",
  secondaryRow: "mt-1 text-xs text-gray-500",
  secondaryRowEmpty: "inline-block",
  footer: "group/footer border-t border-solid border-gray-200",
  footerSticky: "relative group/footer-fixed",
  footerRow: "",
  footerCell: "",
  footerStickyRow: `
    fixed bottom-0 -ml-px border border-b border-gray-200 bg-white
    collapse group-[]/footer-fixed:[visibility:inherit]
  `,
  empty: "my-8",
  i18n: {
    noItems: "There is no data in the table yet.",
    noResultsForFilters: "No results were found for the specified filters.",
    today: "today",
    tomorrow: "tomorrow",
  },
  defaultVariants: {
    nesting: null,
    compact: false,
    selectable: false,
    stickyHeader: false,
    stickyFooter: false,
  },
};
