export default /*tw*/ {
  wrapper: "relative",
  headerCellGeneral: "p-4 text-sm font-normal text-gray-500 text-left",
  headerCounterGeneral: "mr-3 font-medium text-sm text-gray-900",
  stickyHeader: "fixed top-0 flex items-center z-30 overflow-hidden rounded-none border",
  stickyHeaderRow: "border-gray-200 bg-white",
  stickyHeaderCell: "flex-none whitespace-nowrap",
  stickyHeaderCheckbox: "",
  stickyHeaderCounter: "absolute top-4 left-11 bg-gradient-to-r from-white from-80%",
  stickyHeaderLoader: "",
  stickyHeaderActions: "absolute rounded-t-lg border-blue-200 bg-blue-50",
  stickyHeaderActionsCheckbox: "",
  stickyHeaderActionsCounter: "-ml-2",
  tableWrapper: "border border-gray-200 rounded-lg bg-white",
  table: "min-w-full border-none text-sm w-full",
  header: "border-b border-gray-200",
  headerRow: "",
  headerCell: "",
  headerCellCheckbox: "w-10",
  headerCheckbox: "",
  headerCounter: "absolute top-4 left-11 bg-gradient-to-r from-white from-80% mt-px ml-px",
  headerLoader: "absolute !top-auto",
  body: "group/body divide-none",
  bodyRow: "hover:bg-gray-50",
  bodyRowChecked: "bg-gray-100 transition duration-100",
  bodyRowBefore: "!p-0",
  bodyRowBeforeCell: "py-1",
  bodyRowAfter: "!p-0",
  bodyRowAfterCell: "py-1",
  bodyRowDateSeparator: "",
  bodyCell: "",
  bodyCellSecondary: "mt-1 text-xs text-gray-500",
  bodyCellSecondaryEmpty: "inline-block",
  bodyCellCheckbox: "first:px-4", // try to remove first
  bodyCellDateSeparator: "",
  bodyCellNestedWrapper: "flex items-center",
  bodyCellNested: "flex relative -top-px",
  bodyCellNestedExpandIcon: "mr-2 rounded-sm bg-gray-200",
  bodyCellNestedExpandIconName: "add",
  bodyCellNestedCollapseIcon: "mr-2 rounded-sm bg-gray-200",
  bodyCellNestedCollapseIconName: "remove",
  bodyCheckbox: "",
  bodyDateSeparator: "",
  bodyEmptyState: "my-8",
  footer: "group/footer border-t border-solid border-gray-200",
  footerRow: "",
  footerCell: "",
  stickyFooter: "relative group/footer-fixed",
  stickyFooterRow: `
    fixed bottom-0 -ml-px border border-b border-gray-200 bg-white
    collapse group-[]/footer-fixed:[visibility:inherit]
  `,
  i18n: {
    noData: "There is no data in the table.",
  },
  defaultVariants: {
    nesting: false,
    compact: false,
    selectable: false,
    stickyHeader: false,
    stickyFooter: false,
  },
};
