export default /*tw*/ {
  wrapper: "p-3 pb-4 w-64 border border-gray-300 rounded-dynamic bg-white shadow overflow-hidden focus:outline-none",
  navigation: "mb-2 pb-2 border-b flex items-center justify-between",
  viewSwitchButton: "{UButton} -ml-3 pl-3 text-sm rounded-l-none",
  nextPrevWrapper: {
    base: "flex",
    variants: {
      range: {
        true: "justify-between items-center w-full",
      },
    },
  },
  nextPrevButton: "{UButton}",
  dayView: "",
  weekDays: "grid grid-cols-7",
  weekDay: "flex size-8 items-center justify-center text-xs uppercase text-gray-500",
  days: "grid grid-cols-7",
  dateInRange: "bg-brand-100 text-brand-900 hover:!bg-brand-200 rounded-none",
  edgeDateInRange: "rounded-dynamic bg-brand-200 text-brand-900 hover:bg-brand-200",
  firstDateInRange: "rounded-r-none",
  lastDateInRange: "rounded-l-none",
  anotherMonthDate: "hover:bg-brand-100 text-gray-400",
  activeDate: "bg-brand-100 hover:bg-brand-100",
  selectedDate: "bg-brand-600 text-white hover:bg-brand-600 hover:text-white",
  currentDate: "hover:bg-brand-100 border-2 border-brand-600",
  day: `{UButton} rounded-dynamic size-9 w-auto`,
  currentDay: "",
  dayInRange: "",
  currentDayInRange: "",
  anotherMonthDay: "",
  firstDayInRange: "",
  anotherMonthFirstDayInRange: "",
  lastDayInRange: "",
  anotherMonthLastDayInRange: "",
  selectedDay: "",
  activeDay: "",
  monthView: "grid grid-cols-4 items-center justify-center",
  month: "{UButton} mx-auto flex h-12 w-full rounded-dynamic",
  currentMonth: "",
  currentMonthInRange: "",
  lastMonthInRange: "",
  firstMonthInRange: "",
  singleMonthInRange: "rounded-dynamic",
  monthInRange: "",
  selectedMonth: "",
  activeMonth: "",
  yearView: "grid grid-cols-4 items-center justify-center",
  year: "{UButton} mx-auto flex h-12 w-full rounded-dynamic",
  currentYear: "",
  currentYearInRange: "",
  firstYearInRange: "",
  lastYearInRange: "",
  yearInRange: "",
  singleYearInRange: "rounded-dynamic",
  selectedYear: "",
  activeYear: "",
  timepicker: "mt-2 pl-1 pt-3 text-sm flex items-center justify-between gap-2 border-t border-brand-200",
  timepickerLabel: "w-full",
  timepickerInputWrapper: "flex items-center gap-px rounded-dynamic border border-brand-300",
  timepickerInput: "w-11 border-none px-2.5 py-1.5 text-center text-sm focus:ring-brand-700/15",
  timepickerInputHours: "rounded-l-dynamic",
  timepickerInputMinutes: "",
  timepickerInputSeconds: "rounded-r-dynamic",
  timepickerSubmitButton: "{UButton} py-2 border-0",
  i18n: {
    weekdays: {
      shorthand: {
        sunday: "Sun",
        monday: "Mon",
        tuesday: "Tue",
        wednesday: "Wed",
        thursday: "Thu",
        friday: "Fri",
        saturday: "Sat",
      },
      longhand: {
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
      },
      userFormat: {
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
      },
    },
    months: {
      shorthand: {
        january: "Jan",
        february: "Feb",
        march: "Mar",
        april: "Apr",
        may: "May",
        june: "Jun",
        july: "Jul",
        august: "Aug",
        september: "Sep",
        october: "Oct",
        november: "Nov",
        december: "Dec",
      },
      longhand: {
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
      },
      userFormat: {
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
      },
    },
    timeLabel: "Time",
    okLabel: "Ok",
  },
  defaults: {
    userDateFormat: "j F, Y",
    userDateTimeFormat: "j F, Y - H:i:S",
    range: false,
    timepicker: false,
    dateFormat: undefined,
    dateTimeFormat: undefined,
    maxDate: undefined,
    minDate: undefined,
    /* icons */
    viewSwitchIcon: "keyboard_arrow_down",
    nextIcon: "keyboard_arrow_right",
    prevIcon: "keyboard_arrow_left",
  },
};
