export default /*tw*/ {
  wrapper: "p-3 w-[19rem] border border-gray-300 rounded-dynamic bg-white shadow overflow-hidden focus:outline-none",
  navigation: "mb-2 pb-2 border-b flex items-center justify-between",
  viewSwitchButton: "{UButton}",
  nextPrevButton: "{UButton}",
  dayView: "",
  weekDays: "grid grid-cols-7 justify-items-center gap-1",
  weekDay: "flex size-8 items-center justify-center text-xs capitalize text-gray-500 font-medium",
  days: {
    base: "grid grid-cols-7 justify-items-center gap-0.5",
    variants: {
      range: {
        true: "gap-0 gap-y-0.5",
      },
    },
  },
  dateInRange: "bg-brand/5 !text-brand-900 hover:bg-brand/15 rounded-none",
  edgeDateInRange: "",
  firstDateInRange: "rounded-r-none",
  lastDateInRange: "rounded-l-none",
  anotherMonthDate: "text-gray-400",
  activeDate: "bg-brand-100",
  selectedDate: "",
  currentDate: "border-2 border-brand-600",
  day: "{UButton} size-9 w-full",
  currentDay: "",
  dayInRange: "",
  currentDayInRange: "",
  anotherMonthDay: "font-normal",
  firstDayInRange: "",
  anotherMonthFirstDayInRange: "",
  lastDayInRange: "",
  currentLastDayInRange: "",
  currentFirstDayInRange: "",
  anotherMonthLastDayInRange: "",
  selectedDay: "",
  activeDay: "",
  monthView: "grid grid-cols-4 justify-items-center gap-1",
  month: "{UButton} mx-auto flex h-12 w-full",
  currentMonth: "",
  currentMonthInRange: "",
  currentLastMonthInRange: "",
  currentFirstMonthInRange: "",
  lastMonthInRange: "",
  firstMonthInRange: "",
  singleMonthInRange: "rounded-dynamic",
  singleCurrentMonthInRange: "rounded-dynamic",
  monthInRange: "",
  selectedMonth: "",
  activeMonth: "",
  yearView: "grid grid-cols-4 justify-items-center gap-1",
  year: "{UButton} mx-auto flex h-12 w-full",
  currentYear: "",
  currentYearInRange: "",
  firstYearInRange: "",
  lastYearInRange: "",
  yearInRange: "",
  singleYearInRange: "rounded-dynamic",
  singleCurrentYearInRange: "rounded-dynamic",
  currentLastYearInRange: "",
  currentFirstYearInRange: "",
  selectedYear: "",
  activeYear: "",
  timepicker: "mt-2 pl-1 pt-3 text-sm flex items-stretch justify-between gap-2 border-t border-gray-200",
  timepickerLabel: "w-full self-center",
  timepickerInputWrapper: "flex items-center rounded-dynamic border border-brand-300",
  timepickerInput: "w-10 border-none px-1.5 py-1.5 text-center text-sm focus:ring-0 focus:placeholder:text-gray-900",
  timepickerInputHours: "rounded-l-dynamic",
  timepickerInputMinutes: "",
  timepickerInputSeconds: "rounded-r-dynamic",
  timepickerSubmitButton: "{UButton} py-2 border-0",
  i18n: {
    weekdays: {
      shorthand: {
        sunday: "Sun",
        monday: "Mon",
        tuesday: "Tue",
        wednesday: "Wed",
        thursday: "Thu",
        friday: "Fri",
        saturday: "Sat",
      },
      longhand: {
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
      },
      userFormat: {
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
      },
    },
    months: {
      shorthand: {
        january: "Jan",
        february: "Feb",
        march: "Mar",
        april: "Apr",
        may: "May",
        june: "Jun",
        july: "Jul",
        august: "Aug",
        september: "Sep",
        october: "Oct",
        november: "Nov",
        december: "Dec",
      },
      longhand: {
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
      },
      userFormat: {
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
      },
    },
    timeLabel: "Time",
    okLabel: "Ok",
  },
  defaults: {
    userDateFormat: "j F, Y",
    userDateTimeFormat: "j F, Y - H:i:S",
    range: false,
    timepicker: false,
    dateFormat: undefined,
    dateTimeFormat: undefined,
    tabindex: 1,
    /* icons */
    viewSwitchIcon: "keyboard_arrow_down",
    nextIcon: "keyboard_arrow_right",
    prevIcon: "keyboard_arrow_left",
  },
};
