export default /*tw*/ {
  wrapper: "p-3 pb-4 w-64 border border-gray-300 rounded-dynamic bg-white shadow overflow-hidden focus:outline-none",
  navigation: "mb-2 pb-2 border-b flex items-center justify-between",
  navigationSwitchViewButton: "{UButton} -ml-3 pl-3 text-sm rounded-l-none",
  dayViewSwitchLabel: "flex gap-1",
  dayViewSwitchLabelMonth: "",
  dayViewSwitchLabelIcon: "",
  nextPrevWrapper: {
    base: "flex",
    variants: {
      range: {
        true: "justify-between items-center w-full",
      },
    },
  },
  nextPrevButton: "{UButton}",
  dayView: "",
  weekDays: "grid grid-cols-7",
  weekDay: "flex size-8 items-center justify-center text-xs uppercase text-gray-500",
  days: "grid grid-cols-7",
  day: "mx-auto size-8 rounded-dynamic text-sm hover:bg-brand-100 hover:text-brand-600 disabled:opacity-50 disabled:cursor-not-allowed",
  activeDay: "bg-brand-100 hover:bg-brand-100",
  inRangeFirstDay: "rounded-dynamic rounded-r-none bg-brand-200 text-brand-900 hover:bg-brand-200",
  inRangeLastDay: "rounded-dynamic rounded-l-none bg-brand-200 text-brand-900 hover:bg-brand-200",
  inRangeDay: "bg-brand-100 text-brand-900 hover:!bg-brand-200 rounded-none",
  selectedDay: "bg-brand-600 text-white hover:bg-brand-600 hover:text-white",
  currentDay: "hover:bg-brand-100 border-2 border-brand-600",
  anotherMonthDay: "hover:bg-brand-100 text-gray-400",
  monthView: "grid grid-cols-4 items-center justify-center",
  month: "{UButton} mx-auto flex h-12 w-full rounded-dynamic",
  selectedMonth: "bg-brand-900 hover:bg-brand-900 text-white",
  activeMonth: "bg-brand-100",
  currentMoth: "border-2 border-brand-900",
  yearView: "grid grid-cols-4 items-center justify-center",
  year: "{UButton} mx-auto flex h-12 w-full rounded-dynamic",
  currentYear: "border-2 border-brand-900",
  selectedYear: "bg-brand-600 hover:bg-brand-600 text-white",
  activeYear: "bg-brand-100",
  timepicker: "mt-2 pl-1 pt-3 text-sm flex items-center justify-between gap-2 border-t border-brand-200",
  timepickerLabel: "w-full",
  timepickerInputWrapper: "flex items-center gap-px rounded-dynamic border border-brand-300",
  timepickerInput: "w-11 border-none px-2.5 py-1.5 text-center text-sm focus:ring-brand-700/15",
  timepickerInputHours: "rounded-l-dynamic",
  timepickerInputMinutes: "",
  timepickerInputSeconds: "rounded-r-dynamic",
  timepickerSubmitButton: "{UButton} py-2 border-0",
  i18n: {
    weekdays: {
      shorthand: {
        sunday: "Sun",
        monday: "Mon",
        tuesday: "Tue",
        wednesday: "Wed",
        thursday: "Thu",
        friday: "Fri",
        saturday: "Sat",
      },
      longhand: {
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
      },
      userFormat: {
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
      },
    },
    months: {
      shorthand: {
        january: "Jan",
        february: "Feb",
        march: "Mar",
        april: "Apr",
        may: "May",
        june: "Jun",
        july: "Jul",
        august: "Aug",
        september: "Sep",
        october: "Oct",
        november: "Nov",
        december: "Dec",
      },
      longhand: {
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
      },
      userFormat: {
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
      },
    },
    timeLabel: "Time",
    okLabel: "Ok",
  },
  defaults: {
    dayViewSwitchLabelIcon: "keyboard_arrow_right",
    nextIcon: "keyboard_arrow_right",
    prevIcon: "keyboard_arrow_left",
    userFormat: "j F, Y",
    range: false,
    timepicker: false,
    dateFormat: undefined,
    maxDate: undefined,
    minDate: undefined,
  },
};
