export default /*tw*/ {
  wrapper: "p-3 pb-4 w-64 border border-brand-300 rounded-lg bg-white shadow overflow-hidden focus:outline-none",
  navigation: "mb-2 pb-2 border-b flex items-center justify-between",
  navigationSwitchViewButton: "-ml-3 pl-3 text-sm rounded-l-none",
  dayViewSwitchLabel: "flex gap-1",
  dayViewSwitchLabelMonth: "text-brand-900",
  dayViewSwitchLabelIcon: "",
  dayViewSwitchLabelIconName: "keyboard_arrow_right",
  nextPrevWrapper: {
    base: "flex",
    variants: {
      range: {
        true: "justify-between items-center w-full",
      },
    },
  },
  nextPrevButton: "",
  nextIcon: "",
  nextIconName: "keyboard_arrow_right",
  prevIcon: "",
  prevIconName: "keyboard_arrow_left",
  dayView: "",
  weekDays: "grid grid-cols-7",
  weekDay: "flex size-8 items-center justify-center text-xs uppercase text-brand-500",
  days: "grid grid-cols-7",
  day: "mx-auto size-8 rounded-lg text-sm hover:bg-brand-100 disabled:opacity-50 disabled:cursor-not-allowed",
  activeDay: "bg-brand-100 hover:bg-brand-100",
  inRangeFirstDay: "rounded-none rounded-l-lg bg-brand-200 text-brand-900 hover:bg-brand-200",
  inRangeLastDay: "rounded-none rounded-r-lg bg-brand-200 text-brand-900 hover:bg-brand-200",
  inRangeDay: "bg-brand-100 text-brand-900 hover:!bg-brand-200 rounded-none",
  selectedDay: "bg-brand-900 text-white hover:bg-brand-900",
  currentDay: "hover:bg-brand-100 border-2 border-brand-900",
  anotherMonthDay: "hover:bg-brand-100 text-brand-400",
  monthView: "grid grid-cols-4 items-center justify-center",
  month: "mx-auto flex h-12 w-full rounded-lg hover:!bg-brand-900 hover:text-white",
  selectedMonth: "bg-brand-900 hover:bg-brand-900 text-white",
  activeMonth: "bg-brand-100",
  yearView: "grid grid-cols-4 items-center justify-center",
  year: "mx-auto flex h-12 w-full rounded-lg hover:!bg-brand-900 hover:text-white",
  selectedYear: "bg-brand-900 hover:bg-brand-900 text-white",
  activeYear: "bg-brand-100",
  timepicker: "mt-2 pl-1 pt-3 text-sm flex items-center justify-between gap-2 border-t border-brand-200",
  timepickerLabel: "w-full",
  timepickerInputWrapper: "flex items-center gap-px rounded-lg border border-brand-300",
  timepickerInput: "w-11 border-none px-2.5 py-1.5 text-center text-sm focus:ring-brand-500",
  timepickerLeftInput: "rounded-l-lg",
  timepickerRightInput: "rounded-r-lg",
  timepickerSubmitButton: "py-2 focus:ring-0 border-0",
  i18n: {
    weekdays: {
      shorthand: {
        sunday: "Sun",
        monday: "Mon",
        tuesday: "Tue",
        wednesday: "Wed",
        thursday: "Thu",
        friday: "Fri",
        saturday: "Sat",
      },
      longhand: {
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
      },
      userFormat: {
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
      },
    },
    months: {
      shorthand: {
        january: "Jan",
        february: "Feb",
        march: "Mar",
        april: "Apr",
        may: "May",
        june: "Jun",
        july: "Jul",
        august: "Aug",
        september: "Sep",
        october: "Oct",
        november: "Nov",
        december: "Dec",
      },
      longhand: {
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
      },
      userFormat: {
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
      },
    },
    timeLabel: "Time",
    okLabel: "Ok",
  },
  defaultVariants: {
    userFormat: "F j, Y",
    range: false,
    timepicker: false,
    dateFormat: undefined,
    maxDate: undefined,
    minDate: undefined,
  },
};
