export default /*tw*/ {
  wrapper: "relative",
  input: "{UInput}",
  buttonWrapper: `
    flex rounded-dynamic max-md:justify-between
    focus-within:ring-dynamic focus-within:ring-offset-dynamic focus-within:ring-brand-700/15
  `,
  button: "{UButton} shrink-0 grow rounded-none",
  buttonActive: "",
  buttonWrapperActive: "ring-dynamic ring-offset-dynamic ring-brand-700/15",
  shiftRangeButton: `
    first:rounded-dynamic first:rounded-r-none
    last:rounded-dynamic last:rounded-l-none
  `,
  menu: {
    base: `
      absolute z-40 mb-3 w-80 overflow-hidden rounded-dynamic
      border border-brand-300 bg-white p-2 shadow focus:outline-none
    `,
    variants: {
      openDirectionX: {
        left: "left-0 right-auto",
        right: "right-0 left-auto",
      },
      openDirectionY: {
        top: "bottom-full mt-0",
        bottom: "top-full mb-0",
      },
    },
    compoundVariants: [
      { error: true, variant: "input", class: "-mt-3" },
      { description: true, variant: "input", class: "-mt-3" },
      { description: false, error: false, variant: "input", class: "mt-2" },
      { error: true, variant: "button", class: "-mt-2" },
      { description: true, variant: "button", class: "-mt-2" },
      { description: false, error: false, variant: "button", class: "mt-3" },
    ],
  },
  menuTransition: {
    enterFromClass: "opacity-0 scale-95",
    enterActiveClass: "transition transform ease-out duration-100",
    enterToClass: "opacity-100 scale-100",
    leaveFromClass: "opacity-100 scale-100",
    leaveActiveClass: "transition transform ease-in duration-75",
    leaveToClass: "opacity-0 scale-95",
  },
  periodsRow: "mb-1 flex min-w-64 gap-1",
  periodButton: "{UButton} h-[3.125rem] w-full",
  periodButtonActive: "!bg-gray-800/20",
  rangeSwitchWrapper: "flex items-center justify-between py-2",
  rangeSwitchButton: "{UButton}",
  rangeSwitchTitle: "font-medium text-sm",
  periodDateList: "",
  periodDateMonthList: "grid grid-cols-3 grid-rows-1 gap-0.5",
  periodDateWeekList: "",
  periodDateYearList: "grid grid-cols-3 grid-rows-1 gap-0.5",
  periodDateQuarterList: "",
  periodDate: "w-full",
  periodDateInRange: "bg-brand-100 text-brand-900 hover:!bg-brand-200 rounded-none",
  edgePeriodDate: "rounded-dynamic bg-brand-200 text-brand-900 hover:bg-brand-200",
  firstPeriodGridDate: "rounded-r-none",
  lastPeriodGridDate: "rounded-l-none",
  firstPeriodListDate: "rounded-b-none",
  lastPeriodListDate: "rounded-t-none",
  periodDateActive: "bg-gray-100",
  customRangeDescription: "",
  rangeInputWrapper: "flex mt-4 -space-x-px group/range-input-wrapper",
  rangeInputFirst: {
    component: "{UInput}",
    label: {
      component: "{ULabel}",
      wrapper: "w-full hover:z-10 focus:z-10",
      description: "hidden",
    },
    block: "focus-within:z-10 focus-within:ring-0 rounded-r-none",
    input: "rounded-r-none",
  },
  rangeInputLast: {
    component: "{UInput}",
    label: {
      component: "{ULabel}",
      wrapper: "w-full hover:z-10 focus:z-10",
      description: "hidden",
    },
    block: "focus-within:z-10 focus-within:ring-0 rounded-l-none",
    input: "rounded-l-none",
  },
  inputRangeError: "text-xs font-normal leading-none mt-2 text-center text-red-500",
  calendar: {
    component: "{UCalendar}",
    wrapper: "p-0 w-full border-none shadow-none",
    navigation: "mb-0 border-none",
    viewSwitchButton: {
      base: "rounded-dynamic px-4",
      rightIcon: "hidden",
    },
    day: "w-full h-10 mb-0.5",
  },
  i18n: {
    ownRange: "Own range",
    week: "Week",
    month: "Month",
    quarter: "Quarter",
    year: "Year",
    dateFormatWithDot: "The date should be in format 'dd.mm.yyyy'.",
    notCorrectMonthNumber: "Wrong month number.",
    notCorrectDayNumber: "Wrong day in month.",
    fromDateGraterThanSecond: "The 'from' date should be less than the 'to' date.",
    toDateSmallerThanFirst: "The 'to' date should be greater than the 'from' date.",
    weekdays: {
      shorthand: {
        sunday: "Sun",
        monday: "Mon",
        tuesday: "Tue",
        wednesday: "Wed",
        thursday: "Thu",
        friday: "Fri",
        saturday: "Sat",
      },
      longhand: {
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
      },
      userFormat: {
        sunday: "Sunday",
        monday: "Monday",
        tuesday: "Tuesday",
        wednesday: "Wednesday",
        thursday: "Thursday",
        friday: "Friday",
        saturday: "Saturday",
      },
    },
    months: {
      shorthand: {
        january: "Jan",
        february: "Feb",
        march: "Mar",
        april: "Apr",
        may: "May",
        june: "Jun",
        july: "Jul",
        august: "Aug",
        september: "Sep",
        october: "Oct",
        november: "Nov",
        december: "Dec",
      },
      longhand: {
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
      },
      userFormat: {
        january: "January",
        february: "February",
        march: "March",
        april: "April",
        may: "May",
        june: "June",
        july: "July",
        august: "August",
        september: "September",
        october: "October",
        november: "November",
        december: "December",
      },
    },
  },
  defaults: {
    size: "md",
    variant: "button",
    openDirectionX: "auto",
    openDirectionY: "auto",
    timepicker: false,
    disabled: false,
    dateFormat: undefined,
    maxDate: undefined,
    minDate: undefined,
    /* icons */
    nextIcon: "keyboard_arrow_right",
    prevIcon: "keyboard_arrow_left",
    ownRangeIcon: "apps",
  },
};
