export const COMPONENT_NAME = "UKey";

export const KEY_SYMBOLS = {
  command: "⌘",
  cmd: "⌘",
  meta: "⌘",
  shift: "⇧",
  alt: "⌥",
  option: "⌥",
  ctrl: "⌃",
  control: "⌃",
  enter: "↵",
  return: "↵",
  delete: "⌫",
  backspace: "⌫",
  escape: "⎋",
  esc: "⎋",
  tab: "⇥",
  capslock: "⇪",
  caps: "⇪",
  up: "↑",
  down: "↓",
  left: "←",
  right: "→",
  pageup: "⇞",
  pagedown: "⇟",
  home: "↖",
  end: "↘",
  space: "␣",
} as const;
